/*
 * iconlin.c - icon file for GNU/Linux
 * Copyright (C) 2008-2010  Alexandre Martins <alemartf(at)gmail(dot)com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include <allegro.h>
/* XPM */
static const char *allegico_xpm[] = {
/* columns rows colors chars-per-pixel */
"128 128 256 2",
"   c #000000E4026B",
".  c #000004020B68",
"X  c #0000065A12C3",
"o  c #000008081717",
"O  c #0000094A1B3C",
"+  c #00010BFE2336",
"@  c #00000E662ADA",
"#  c #000010102626",
"$  c #090912BD26D1",
"%  c #000010352E53",
"&  c #0B0B15962ACB",
"*  c #0D0D186E2ED9",
"=  c #0003117B338C",
"-  c #000019C4358B",
";  c #0E391A453288",
":  c #000414253B97",
">  c #00001AFE3A90",
",  c #0B0B1B1B3B91",
"<  c #11111D1D357E",
"1  c #12931F1F3838",
"2  c #152C22223C53",
"3  c #0000165E4226",
"4  c #0000192045E5",
"5  c #001F195C4A62",
"6  c #08081E1E4B4B",
"7  c #07071F1F5050",
"8  c #000022224419",
"9  c #000026E74C8C",
"0  c #000029294EA4",
"q  c #090920204E4E",
"w  c #16B0258C43AA",
"e  c #18EE267C41EC",
"r  c #1919282845C5",
"t  c #1B9C2BAB4B76",
"y  c #018123235353",
"u  c #0B4B23635313",
"i  c #00002C8954C9",
"p  c #00002A5D5C8F",
"a  c #000027275C5C",
"s  c #13942B2B5999",
"d  c #1E1E2F2F5050",
"f  c #000031565BC9",
"g  c #1D1D31315858",
"h  c #222233335522",
"j  c #23CE35E05A04",
"k  c #29293B3B5E5E",
"l  c #26A738B95BDC",
"z  c #00002D2D6262",
"x  c #000034596540",
"c  c #000034096CC2",
"v  c #00003A5A6C8C",
"b  c #000038386767",
"n  c #1D73348A6262",
"m  c #00003B8A72C1",
"M  c #00003D3D7878",
"N  c #1D9E3BBC7878",
"B  c #2BEC3DFE6262",
"V  c #287E3E3E6913",
"C  c #22A239BA6767",
"Z  c #000040A77441",
"A  c #000043DD7C96",
"S  c #000048487F7F",
"D  c #121246467E7E",
"F  c #2DF443146D27",
"G  c #2EAF40C065E6",
"H  c #325D45456AEA",
"J  c #367649096CED",
"K  c #303042426767",
"L  c #2AEB46C778F8",
"P  c #312146467070",
"I  c #353E4AAC757E",
"U  c #3A154D28732A",
"Y  c #39394E4E7979",
"T  c #35354D4D7979",
"R  c #29AA50507F7F",
"E  c #3C3C51D17D7D",
"W  c #3D3D50507676",
"Q  c #404050507171",
"!  c #000049EA84C4",
"~  c #00004CBA8A8A",
"^  c #000045C58201",
"/  c #000050EA8E5B",
"(  c #000054879447",
")  c #000057579B1A",
"_  c #000059AF9C9C",
"`  c #3EFF554A8095",
"'  c #343457D88686",
"]  c #39395656900F",
"[  c #39E463639393",
"{  c #00005DD7A329",
"}  c #000060CEA6A6",
"|  c #0007655EADA0",
" . c #093C6699AAAA",
".. c #05E668C8AF0E",
"X. c #0B9A69DBAD90",
"o. c #14146D2DAE6E",
"O. c #0C0C6C76B16C",
"+. c #12456F6FB27F",
"@. c #15AB721CB409",
"#. c #1BE57507B522",
"$. c #1F1F7878B7B7",
"%. c #368C6DC3A14B",
"&. c #3A907676AAAA",
"*. c #2177751FB2B2",
"=. c #23237878B636",
"-. c #2B0B7BDBB696",
";. c #24937B7EB99B",
":. c #2A3E7EFFBB36",
">. c #2F2F7777B0B0",
",. c #35757E7EB676",
"<. c #414157578383",
"1. c #43C359DA8605",
"2. c #46465C7A89A7",
"3. c #48485F5F8B95",
"4. c #4B5461E68E97",
"5. c #444460608D8D",
"6. c #575767678787",
"7. c #4E3F657C92B0",
"8. c #481D69699797",
"9. c #505067679494",
"0. c #525269699696",
"q. c #55426BF599A3",
"w. c #58586F6F9C9C",
"e. c #5B4D71EE9F1B",
"r. c #565670709E9E",
"t. c #626271718F8F",
"y. c #65607471918E",
"u. c #4D4D6B6BA7A7",
"i. c #46B47752A83A",
"p. c #51517434A2E2",
"a. c #5E337575A1AF",
"s. c #50FB7A24A9A9",
"d. c #58AE7923AB00",
"f. c #5D5D7A7AB4B4",
"g. c #6060767EA3AB",
"h. c #636379F9A6AD",
"j. c #663E7C86A9B3",
"k. c #68687E7EABAB",
"l. c #2E2E8101BCBC",
"z. c #34398478BE69",
"x. c #395C876DBF88",
"c. c #3E3E88DEBF69",
"v. c #33338080B7B7",
"b. c #5C5C8100AEAE",
"n. c #4B4B8242B2F2",
"m. c #44848B0ABEBE",
"M. c #4B4B8B0ABCFC",
"N. c #57578484B3B3",
"B. c #58589090BFBF",
"V. c #6B68817EADAD",
"C. c #64648282AFAF",
"Z. c #64648484B1B1",
"A. c #6ECC850AB13C",
"S. c #63638908B5F5",
"D. c #6D6D89BCB5B5",
"F. c #62628E38BB10",
"G. c #69698E0EBA39",
"H. c #65658282BBBB",
"J. c #71718787B3B3",
"K. c #74728A91B6BD",
"L. c #774B8D91B8E0",
"P. c #79798F8FBABA",
"I. c #64CB912ABDBD",
"U. c #7D8A934FBE1F",
"Y. c #77779393BDBD",
"T. c #3D4389E1C16A",
"R. c #43CE8E0FC37E",
"E. c #4D4D8F8FC0C0",
"W. c #4B679314C5FD",
"Q. c #50A0955CC74C",
"!. c #5A5A943EC26C",
"~. c #5D9D9A19C6C6",
"^. c #52529797C8C8",
"/. c #5558991AC94A",
"(. c #5B679C1FCB49",
"). c #71718C8CC140",
"_. c #63AC9B2DC6C6",
"`. c #60CD9F7DCC86",
"'. c #683D97EDC3C3",
"]. c #7AFA94D4C302",
"[. c #7D7D9C5CC585",
"{. c #76A19B1BC645",
"}. c #6C6C8989C0C0",
"|. c #6450A194CDBF",
" X c #69B0A4FACF18",
".X c #730CA50BCCFF",
"XX c #7CFDA625CD0C",
"oX c #75DCA90FCF35",
"OX c #7878A9A9CECE",
"+X c #6D6AA725D0D0",
"@X c #6F6FA8A8D1D1",
"#X c #745AABD5D384",
"$X c #7A84AF15D535",
"%X c #7E74B228D6D4",
"&X c #81819696C1C1",
"*X c #849E99CCC3E7",
"=X c #88969DABC6D4",
"-X c #83D99BF1CB75",
";X c #8B359F9FC8F3",
":X c #83EAA3D6CAFD",
">X c #8CA4A1D5CA0C",
",X c #89DFAA54CF79",
"<X c #8585AAAACFCF",
"1X c #919AA4C7CBE9",
"2X c #9589A8B4CED4",
"3X c #82ADADADD1D1",
"4X c #8C8CADADD251",
"5X c #9408AB7CD1D1",
"6X c #9B99AD35D1E2",
"7X c #82A7B3F5D773",
"8X c #8A8AB3CAD503",
"9X c #8585B6B6D8D8",
"0X c #88ABB7A5D9C7",
"qX c #8CA6BA60DA8D",
"wX c #8E8EB8B8D7D7",
"eX c #9191B1B1D48B",
"rX c #9E79B168D5D5",
"tX c #925FBB88D9A6",
"yX c #9A33BF58DB41",
"uX c #9312B9B9D6D6",
"iX c #A31DB4B1D6D7",
"pX c #A475B670DA1F",
"aX c #A70DB8EBDBDB",
"sX c #AAB1BB45DAEF",
"dX c #B0B0BFBFDDE1",
"fX c #9E1EC140DC5C",
"gX c #A4EDC4E9DD94",
"hX c #A953C7C7DEDE",
"jX c #ABABC973DF89",
"kX c #B24EC1D2DFDD",
"lX c #AD7ACB98E248",
"zX c #A5A5C7C7E0E0",
"xX c #B6B6C5C0E1DC",
"cX c #B979C747E2E2",
"vX c #B1B1CE0DE322",
"bX c #BC3DC9CAE3E3",
"nX c #B6B6D110E464",
"mX c #BCBCD429E610",
"MX c #C0C0CDCDE6E6",
"NX c #C1C1D757E767",
"BX c #C4F7D9D9EA1C",
"VX c #CACADC0EE982",
"CX c #D0D0DDDDE8E8",
"ZX c #D466E2E2EDED",
"AX c #DBDBE690EF99",
"SX c #DBDBE791F146",
"DX c #DFDFEAEAF1F1",
"FX c #E261E968EFEF",
"GX c #E472ECCFF381",
"HX c #E9E9EFEFF575",
"JX c #ED00F254F70A",
"KX c #EDEDF3F3F8F8",
"LX c #F372F6F6F9DF",
"PX c #F75DF9C6FB94",
"IX c #FFF4FFF7FFF9",
"UX c None",
/* pixels */
"UXUXUXUXUXUXUXUXUXUX                                                                                                                                                                                                                        UXUXUXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUX      , H 6.t.y.y.y.y.t.y.t.y.y.y.y.y.y.t.y.y.y.y.y.y.y.y.y.y.y.t.y.y.y.y.y.t.y.y.t.y.y.t.y.y.t.y.t.y.y.y.y.y.y.t.y.y.y.y.y.y.y.y.y.y.y.t.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.t.y.y.y.y.y.t.y.y.y.y.y.y.y.y.y.y.y.t.y.6.Q r X     UXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUX  . C L.pXsXsXkXkXdXkXkXkXkXkXkXkXdXkXdXkXkXdXdXkXkXkXkXkXdXkXdXkXkXdXdXkXdXkXkXdXkXkXkXdXdXkXkXkXkXkXkXkXdXkXdXkXkXdXdXkXkXdXkXkXdXkXdXkXkXdXdXkXkXkXkXkXdXkXdXkXkXdXdXkXkXdXkXkXdXkXdXkXkXdXdXkXkXkXkXkXdXkXdXkXxXsXsXpXpX-X` +     UXUXUXUXUXUX",
"UXUXUXUXUX    : f.pXpXdXkXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXMXxXaXpXiX].s     UXUXUXUXUX",
"UXUXUXUX    u &XiXsXbXbXMXMXbXMXbXbXMXbXbXMXMXMXkXMXbXMXbXMXbXMXMXbXbXbXbXMXbXMXbXbXbXMXbXbXbXMXMXbXMXbXbXbXbXbXbXMXbXbXMXMXMXbXbXMXbXbXMXbXMXMXkXMXMXMXbXMXbXbXbXbXbXbXMXMXMXMXbXbXMXbXbXMXMXMXkXMXbXMXbXbXbXMXMXbXbXbXMXMXbXMXbXbXMXbXbXxXaXpX5XN     UXUXUXUX",
"UXUXUXUX  6 [.iXiXbXbXbXbXkXbXbXbXbXbXbXbXxXkXbXMXMXkXMXbXxXbXxXbXbXbXbXbXkXMXbXbXbXbXbXbXbXbXbXkXbXxXbXbXbXbXbXbXbXbXbXbXkXbXMXbXxXbXbXkXbXkXbXMXMXkXbXbXxXbXbXbXbXbXbXbXkXbXkXbXbXbXbXbXxXkXbXMXMXkXMXbXbXbXxXbXbXbXbXbXkXbXMXxXbXbXxXbXbXbXsXpX5XN     UXUXUX",
"UXUXUX  @ }.rXpXkXbXbXbXkXkXkXbXxXxXxXxXkXbXkXbXkXkXbXkXxXxXxXxXkXbXbXbXkXkXkXkXxXxXxXxXkXxXxXbXbXkXbXxXxXxXxXxXkXbXkXbXkXkXkXkXxXxXxXbXxXbXkXbXkXkXbXkXxXxXxXxXkXbXkXbXkXkXkXMXxXxXxXxXkXbXkXbXkXkXbXkXxXxXxXxXkXbXbXbXkXkXkXkXxXxXxXxXxXxXxXkXpXrX1Xu   UXUXUX",
"UXUX  X [ rXrXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXbXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXbXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXxXxXkXkXkXkXkXkXkXpX6XH.O   UXUX",
"UXUX  6 1X6XaXkXkXdXdXdXdXdXdXdXkXkXdXdXdXdXdXdXkXkXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXkXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXkXkXdXdXkXkXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXkXdXdXkXdXdXdXdXdXdXdXdXdXdXdXdXdXdXkXdXdXdXdXdXdXdXdXkXsXrX6XL   UXUX",
"UX    u.6XrXsXsXsXdXsXsXsXsXdXsXsXsXsXsXdXsXsXsXdXdXsXdXsXdXsXsXsXsXdXsXdXsXdXsXdXsXsXdXsXsXdXsXdXdXsXsXsXsXdXsXsXdXsXsXdXsXsXsXsXsXsXsXsXsXsXsXdXdXsXdXdXsXdXsXsXdXsXdXsXsXsXdXsXsXdXsXsXsXsXsXkXdXsXdXdXsXsXsXdXsXdXsXsXsXsXsXdXsXsXsXsXdXsXsXdXsXpX6X).+   UX",
"UX  : ;X2XiXaXaXsXsXsXaXsXsXsXsXsXsXsXsXsXiXsXsXsXsXsXsXsXsXsXsXsXsXsXsXiXsXsXsXiXsXsXsXsXsXsXsXiXsXsXsXsXsXpXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXiXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXsXaXsXsXsXiXsXsXsXsXsXsXiXsXsXsXsXsXsXiXsXsXsXpXaXsXaXaXpX6X5Xn   UX",
"UX  L 5X6XiXiXpXiXpXpXpXiXiXiXiXiXiXiXsXiXiXsXiXiXiXiXiXiXiXiXiXsXiXiXiXiXsXiXiXiXiXpXiXiXiXiXiXiXsXiXiXsXiXiXiXiXiXiXiXiXiXiXsXiXiXsXiXiXiXiXsXiXiXiXiXiXsXiXiXiXiXiXiXiXiXiXiXiXiXiXpXpXiXpXpXiXiXsXiXiXsXiXiXiXsXiXiXsXiXiXiXiXiXsXiXiXpXaXiXpXaXpXiX2Xu.  UX",
"UX  d.1X2XiXiXiXiXrXiXrXiX6XiXiXiXiXiXiXiX6XiXiXiXiXiX6XiXiXiXiXiX6XiXiXiXiXiX6XiXiX6XiXiXiXrXiXiXiXiXiXiXiXiXiXiX6XiXiX6XiXiX6XiXiXiXiXiX6XiXiXiXiXiX6X6XiX6XiXiXiX6XiXiXiXiXiXiXiXiXiXiXrXiXiXiXiXiXiX6XiXiX6X6XiXiX6XiXiXiXiXiXiXiXiXiXiX6XiXiXiXiX6X2X].+   ",
"  X ).1X2X6X6X6X6X6X6X6XrX6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6XiX6X6X6X6X6X6X6X6X6X6X6X6X6X6XiX6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6XiX6X6X6X6X6XrX6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6X6XrX6X6X6X6X6X6XrX6X6X6X6X1X1X,   ",
"  + >X1X1X6X6X5X6X6X6X6X6X6X6X2X2X6X6X6X6X6X2X6X6X6X6X6X6X6X6X6X6X6X2X6X6X6X6X6X6X6X6X6X2X6X6X6X6X6X2X6X6X2X6X6X6X6X2X6X6X6X6X6X2X6X6X6X6X6X2X6X6X6X6X6X6X6X6X6X2X6X6X6X6X2X6X2X6X2X6X6X6X6X6X6X6X6X2X6X6X6X6X6X6X6X6X6X6X6X6X2X2X6X6X6X6X2X6X6X6X6X6X6X1X>Xg   ",
"  , >X>X>X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X1X2X2X2X2X2X2X2X2X2X2X2X1X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X1X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X1X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X5X1X2X1X>X>XH   ",
"  2 1X;X=X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X2X4X8XeXeXeXuXeXeXeXeX5X4X5X1X>X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1X=X;XU   ",
"  e *X;X*X1X;X1X1X=X1X1X;X;X1X;X;X>X>X;X;X1X;X>X1X;X>X>X>X>X>X;X>X;X;X>X>X>X>X;X>X>X>X;X;X;X>X>X>X>X>X;X>X>X>X;X>X>X>X;X>X>X>X,X1X1X4XwX0XwXfXwXqXqXwXwXqXqXqXwXqXqXqXqXqXqXwX8X4X>X>X>X;X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X;X>X>X>X>X1X;X>X>X>X>X;X=X;XQ   ",
"  e =X=X=X=X=X=X*X=X=X=X=X=X;X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X=X;X*X;X=X;X=X=X=X;X=X;X-X-X4X9X9X9X0X0X0X0X0X%X9X0X0X0X0X9X0X0X0X0X0X0X0X0X0X0X0X0X0X0X7X,X>X=X*X=X=X=X=X=X=X=X=X=X=X>X=X=X=X=X=X=X=X=X=X;X=X=X=X=X=X=X=X=X=XQ   ",
"  e *X*X*X*X*X*X*X*X*X*X*X*X=X*X=X*X*X*X*X*X*X*X*X*X*X*X*X=X*X*X=X&X=X=X=X&X=X*X*X*X*X=X=X*X*X*X*X*X*X*X*X*X*X*X*X:X3X7X9X9X0X0X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X8X3X:X*X*X=X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*X*XU   ",
"  e =X*X*X*X&X*X*X*X&X*X&X*X*X&X*X&X*X*X&X*X*X*X*X*X*X*X*X*X*X*X*X&X*X&X*X&X*X&X*X*X*X*X*X*X*X*X*X*X*X&X*X&X:X3X8X7X7X7X0X%X0X0X9X9X%X9X9X9X9X9X7X7X9X7X9X9X%X9X7X7X7X7X7X7X7X7X9X7X7X%X7X7X7X7X8X7X:X*X*X*X*X&X*X&X*X*X*X&X*X*X*X*X&X*X&X*X*X*X*X*X&X*X&X*XU   ",
"  e &X*X&X&X&X&X&X&X&X&X&X&X&X&X&X&X*XU.&XU.&X&X&X&XU.*XU.*X&XU.&X&X&X&X&X&X&X&X&X&XU.*X*XU.&X&X&X&X&X*X:X7X%X7X%X7X7X7X%X%X%X%X%X%X7X9X%X%X%X%X9X%X%X7X%X9X%X%X7X7X7X7X7X7X7X7X7X%X7X9X7X%X7X7X7X%X7X7X$X*X&X&X&X&X&X&X&X&X&X&X&X&X&X&X&X&X&X&XU.&X&X&X&X&XU   ",
"  2 &XU.&XU.U.U.&XU.U.&XU.&XU.U.U.U.U.*XU.&XU.&XU.U.&XU.U.&XU.U.&XU.&XU.&X&X&XU.U.U.&XU.U.*XU.U.&X[.XX7X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X7X%X%X%X%X%X7X%X%X%X%X%X%X%X%X<XXX&XU.U.&XU.U.U.U.&XU.&XU.U.&XU.U.&XU.U.&X&X&XU   ",
"  2 U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.P.U.U.U.U.U.U.U.U.U.U.U.U.P.U.&XXX$X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X$X%X%X%X%X%X%X%X%X%X%X%X%X%X$X%X%X7XOX[.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.J   ",
"  2 P.U.P.U.P.P.P.U.P.U.P.U.P.U.P.U.U.U.P.U.U.U.U.U.U.U.P.U.U.P.P.P.U.P.U.P.P.P.P.U.P.U.P.U.XX$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X%X%X$X$X$X$X$X$X$X$X$X$X$X%X$X$X%X$X$X$X%X$X$X$X$X$X%X$X%X%X$X%X%X%X%X$X$X%X%X$X$X$XXX].U.U.U.U.P.U.P.P.U.P.U.P.U.P.P.U.P.U.J   ",
"  e P.U.P.P.P.P.P.P.P.P.P.P.P.P.P.P.L.P.P.P.L.P.P.P.P.P.P.P.P.L.P.L.P.P.P.P.P.L.P.P.P.P.[.#X$X%X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X%X#X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X#X%X$X$X$X$X#X$X#X%X#X$X#X#X#X%X$X#X$X#X$X$X$X$X{.L.L.U.P.P.P.P.P.P.P.P.P.P.P.P.P.P.J   ",
"  e P.P.K.P.P.P.L.L.L.L.L.L.L.P.L.L.P.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.P.L.L.L.P.L.Y.OX#X$X#X#X#X$X$X$X#X$X#X$X$X$X#X$X#X$X#X%X#X$X#X#X#X$X#X$X#X$X#X$X$X#X$X$X$X#X$X#X%X#X#X#X$X$X$X$X%X#X#X#X%X#X#X%X#X$X#X$X$X#X$X#X$XoXY.L.P.L.L.L.L.L.L.L.P.P.K.P.L.L.J   ",
"  2 K.K.K.K.K.K.L.K.L.L.K.L.K.K.K.K.K.K.K.K.L.K.K.K.L.K.K.L.K.K.K.L.K.L.L.L.K.L.L.{.#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X$X#X#X$X#X#X#X#X#X#X#X#X#X#X#X#X$X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X{.L.L.L.J.L.L.L.L.K.K.K.L.L.L.J   ",
"  2 K.K.K.K.K.K.J.J.K.J.K.J.K.J.K.K.K.J.J.K.J.K.J.K.K.J.K.J.K.K.L.J.K.K.K.K.K.L..X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X@X#X#X@X#X#X#X@X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X{.K.J.K.L.J.K.J.J.K.K.K.J.J.H   ",
"  1 A.J.J.J.J.A.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.A.D.Y.@X+X#X#X+X+X#X@X#X+X#X+X#X#X#X@X@X@X@X@X@X@X#X@X@X#X@X@X#X@X@X#X@X@X@X@X@X#X@X@X@X#X@X#X@X#X@X#X@X@X@X@X@X@X@X#X@X@X@X+X#X#X#X#X@X@X#X@X#X+X#X@X@X+X.XK.A.J.J.J.J.J.J.J.J.J.J.H   ",
"  2 A.A.A.A.A.A.A.A.A.A.A.J.A.A.A.A.J.A.A.A.A.A.J.A.A.A.A.A.A.A.J.V.V.J.A.'.#X+X X#X+X+X#X+X@X@X@X@X#X+X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X#X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X@X#X@X@X@X@X@X#X+X+X#X+X@X+X#X#X+X XK.A.A.A.A.A.A.A.A.A.A.K   ",
"  2 A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.J.V.J.D. X#X X#X+X@X+X+X+X@X+X+X+X+X+X@X+X+X+X+X+X@X+X@X+X@X+X+X+X+X+X+X+X+X+X+X@X@X@X@X+X@X+X@X@X+X@X+X+X@X+X@X@X@X@X@X@X@X@X+X+X+X+X+X+X+X@X X X#X X X#X X#X X X#X X XJ.A.A.A.A.A.A.A.A.A.K   ",
"  2 A.k.J.k.J.A.k.A.A.k.A.A.V.V.A.V.V.V.A.V.V.V.V.V.V.A.V.A.V.V.V.V.D. X+X+X X+X+X+X+X+X+X+X+X X+X+X+X+X+X+X+X+X+X+X+X X+X+X+X+X+X+X+X+X+X+X+X+X+X+X X+X+X+X+X+X X+X X X+X+X+X X+X+X+X+X+X+X+X+X+X X+X+X+X+X+X+X+X+X+X+X+X+X X+X+X X X@X XV.V.V.V.V.V.V.V.V.K   ",
"  2 A.k.k.k.k.k.k.k.A.k.k.k.V.k.k.V.V.k.V.V.V.V.V.V.V.k.V.V.k.V.V.G. X+X+X X X X X X X+X X X X X X+X|.+X X X X+X X X X X X X X X X X X X X X X X X+X X X X X X X X+X X X X X X X X X X X X X+X+X X X+X+X|.+X X X X+X X X X X X'.Y.I.D.Z.V.V.V.V.V.V.V.V.V.V.K   ",
"  1 k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.j.k.k.k.k.k.j.k.k.k.k.k.G. X X X|.+X|.+X X X X X X X X X|.+X|.+X|. X X X X X X X X X X X|. X X X X X X|. X X X X X|. X X X X X X X X X X X X+X X|. X X|. X X X X+X|. X|. X X XI.G.C.V.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.B   ",
"  1 j.j.j.j.j.j.k.j.j.j.j.j.j.k.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.I.|. X|.|.+X|.|.|.|.|.|.|.|. X|.|.|.+X|.|.|. X|.|.|.|. X|.|. X|.|. X|.|. X|.|. X|. X|.|. X|. X|. X|. X X|.|. X|.|.|.|.|. X|.|.|.|. X|.|.|.|. X|.|.I.C.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.k.B   ",
"  1 h.h.h.h.h.h.h.h.Z.I.'._.|.`.`._.'.I.H.Z.j.h.j.h.h.j.h.h.F.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|._.S.h.j.j.h.j.h.h.h.h.h.h.h.h.h.h.j.h.h.h.h.j.h.h.B   ",
"  1 h.h.h.h.h.g.h.S.`.`.`.|.|.|.`.|._.|.|.`.`.`.I.S.C.h.h.F.|.|.`.|.`.|.`.|.|.|.|.`.|.`.`.`.`.|.|.`.`.|.|.`.|.`.|.|.`.|.`.`.`.`.|.|.|.`.|.`.`.|.`.`.`.|.`.`.|.`.`.|.|.`.`.|.|.`.|.|.`.|.`.|.`.|.`.|.|._.Z.h.h.h.g.h.g.h.h.h.h.h.h.h.h.h.h.h.h.g.h.h.h.h.h.h.k   ",
"  1 g.h.g.g.g.g.a.`.`.`.`.|._.|.`.`.`.`.`.`.`.`.(.`.`._.~.(.|.|.`.`.`.`.`.|.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.(.|.`.|.|.`.`.`.(.|.(.|.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.(.F.a.g.a.a.h.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.a.h.h.a.g.g.k   ",
"  1 y.g.g.a.a.a.b.(.`.(.`._.(.(.`.`.(.`.(.(.(.(.(.|.(.(.(._.(.(.(.`.(.`.(.(.(.`.(.`.(.`.(.`.(.`.(.(.`.(.`.`.(.(.(.`.(.(.(.`.(.`.(.`.(.(.`.(.`.(.`.(.`.(.`.(.`.(.`.(.`.(.(.`.(.`.(.`.(.`.`.(.`.`._.b.a.a.a.a.a.a.g.e.g.e.g.g.e.g.a.a.a.a.a.a.a.g.a.a.a.a.y.g.k   ",
"  < e.e.e.e.e.e.b.`.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.`.`.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.`.`.(.(.(.(.(.(.(.(.(.`.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.!.a.a.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.B   ",
"  < e.e.e.e.e.e.N.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(./.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(./.(.(.(.(.(.(.(.(.(.(./.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.(.B.e.a.r.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.l   ",
"  < w.w.w.w.r.r.d.(./.(./.(./.(.(.(./.(./.(.(.(.(./.(.(./././././.(./.(.^.(.(.(.(.(./.(.(.(.(./.(.(./.(./.(.(.(.(./.(./.(.(././.(.(.(.(.(./././.(.(././.(.(.(./.(.(.(./.(.(.(.^.(.(./.(./.B.r.e.w.w.w.w.e.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.e.w.w.e.q.e.w.w.l   ",
"  < q.w.q.q.q.q.r././././././././././././././././././.(./././././.^.(.^.(.^.^.(././././././././././././././.^././././././././././././././.(././././././././././.^.^.^.(.^./.^.(././././.!.r.q.q.q.q.q.q.q.q.q.q.q.w.q.q.q.q.q.q.q.q.w.q.q.q.q.q.q.q.q.q.q.q.l   ",
"  * q.q.q.q.q.q.0.!././././././././.^./.^././.^./././.^././././.^.^.(.^.^.^.^././.^.^.^.^.^./././.^./././.^.^.^./././.^././.^./.^.^.^.^./.^././.^./.^././.^././.^.^.^.^.^.^.^.(./././.B.r.q.q.0.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.l   ",
"  < 0.0.0.0.9.0.0.M.Q./././.^.Q.^./.^.^.^.^.^.^.^.^.^.^.^./.Q.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.^.^.^.^.^.^.^.^./.Q.Q.n.0.0.0.0.0.0.9.q.0.9.0.0.0.9.0.0.0.9.0.0.q.9.9.9.0.0.9.0.9.q.9.0.0.0.h   ",
"  * 9.9.9.9.9.9.7.p.^.Q.Q.Q.Q.Q.^.W.^.^.^.Q.^.W.^.^.^.W.Q.Q.Q.Q.Q.^.^.Q.^.Q.Q.^.^.^.^.^.^.^.^.^.^.Q.^.^.^.^.^.Q.^.^.^.W.Q.Q.Q.^.^.^.^.^.W.^.^.^.^.^.W.^.^.W.^.W.^.^.^.^.W.^.^.^.Q.Q.W.s.s.i.i.q.7.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.h   ",
"  < 4.7.7.7.7.7.7.9.W.W.Q.W.Q.W.Q.W.W.W.Q.W.W.^.W.W.W.^.W.Q.W.Q.W.W.Q.W.Q.W.W.Q.W.W.^.W.W.W.W.W.Q.W.W.W.W.W.W.^.W.W.W.^.Q.Q.W.W.^.W.W.^.W.^.W.W.Q.W.Q.Q.Q.W.W.^.W.W.W.^.W.^.W.W.Q.W.Q.W.Q.Q.^.W.W.M.n.p.9.7.7.7.7.7.7.7.7.7.7.7.7.9.4.9.7.7.9.4.9.4.9.4.9.9.h   ",
"  * 4.4.4.4.4.4.7.4.s.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W. X8XzXlXlXwX(.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.^.W.^.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.M.i.7.4.4.4.7.4.4.4.7.4.4.4.4.7.4.4.7.4.4.4.4.7.7.h   ",
"  * 4.4.4.4.4.4.3.4.u.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W. XvXJXIXIXIXIXIXIXIXnX/.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.T.^.T.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.n.8.4.4.4.4.4.4.4.4.4.4.4.4.3.4.4.3.7.3.3.3.h   ",
"  * 3.3.3.3.3.3.3.3.3.R.W.W.W.W.W.W.W.W.W.W.W.R.W.R.R.W.W.W.W.W.W.W.W.W.R.W.W.R.W.R.W.(.NXIXIXIXIXIXIXIXIXIXIXIXJX_.R.W.W.R.W.R.W.W.W.T.W.W.T.W.T.W.T.^.T.^.^.T.W.W.W.W.W.W.W.W.R.W.R.W.W.W.W.W.R.W.W.W.R.W.W.W.R.W.n.8.2.5.5.2.3.3.3.3.3.3.3.5.3.3.3.3.3.3.d   ",
"  * 2.2.2.2.2.2.2.2.2.i.R.R.R.R.R.R.R.R.R.T.W.R.R.W.R.R.R.R.R.R.R.R.R.R.R.W.R.R.W.R.wXPXIXIXIXIXIXIXIXIXIXIXIXIXIXKX(.R.R.W.R.W.T.W.T.W.W.T.W.W.W.W.W.T.W.T.W.W.R.R.R.R.R.R.R.R.W.R.W.R.R.R.R.R.R.R.R.W.R.R.R.R.R.R.R.W.i.5.2.2.2.2.2.2.2.2.2.2.1.3.1.3.2.2.d   ",
"  * 1.1.1.1.1.1.1.1.1.5.m.R.R.R.W.T.W.T.R.T.W.T.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.vXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXZXR.R.R.R.R.W.T.W.T.W.T.T.W.T.W.T.W.T.W.T.W.R.R.R.R.R.R.R.R.T.W.R.R.R.R.W.R.R.R.R.R.R.R.R.R.R.R.R.R.R.m.8.` 1.1.1.1.1.1.1.1.1.1.1.1.1.1.d   ",
"  * 1.1.1.1.1.1.1.1.1.1.i.R.R.R.T.W.T.W.T.W.T.W.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.lXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXyXR.R.R.R.W.T.T.W.T.W.W.T.W.T.W.T.W.T.T.T.R.R.R.R.R.R.R.R.T.T.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.T.u.1.1.1.2.1.1.1.1.1.1.1.1.1.1.d   ",
"  & <.<.<.<.<.<.<.<.<.1.[ R.R.R.T.T.W.T.T.W.T.R.R.R.R.R.R.R.T.T.T.R.R.R.R.R.T.qXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXLXW.R.R.T.T.W.T.T.T.T.T.W.T.T.T.W.W.T.W.T.R.R.R.R.R.R.T.T.R.R.R.R.T.T.R.R.R.R.R.R.R.T.T.R.T.R.R.R.R.R.R.T.i.<.<.` ` 1.` 1.<.<.<.<.1.1.t   ",
"  & ` ` ` <.<.Q ` ` ` Q <.,.T.R.R.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.`.IXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXfXm.T.R.T.T.T.T.T.W.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.R.T.T.c.T.T.c.R.T.T.R.T.R.T.T.T.T.T.T.c.&.Q 1.` ` ` ` <.` ` ` ` Q t   ",
"  & E E ` Y ` ` Y ` ` Y ` [ T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.SXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXJXT.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.&.Y Y ` ` ` ` E E E <.E t   ",
"  & E E ` Y Y ` ` Y Y ` E Y x.c.T.T.T.T.T.x.T.x.T.T.T.T.T.T.T.T.T.T.T.T.x.uXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIX XT.x.;.T.T.T.T.T.T.T.T.T.T.T.T.T.T.l.x.T.T.T.T.T.z.T.T.T.T.T.T.T.T.x.x.T.T.T.T.T.T.T.T.T.T.T.T.z.T.T.T.T.T.%.` ` Y Y Y Y E Y Y E r   ",
"  & Y Y Y Y Y Y Y Y Y Y T ' T.T.T.T.T.T.R.x.T.T.T.z.z.z.z.T.T.z.T.T.T.T.R.LXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXlXx.x.T.T.T.T.;.T.T.T.T.T.T.T.T.T.T.T.x.T.x.x.z.z.T.T.z.T.z.z.x.x.x.x.x.x.T.T.z.z.l.T.T.l.T.T.T.T.z.z.T.z.T.T.[ T Y Y Y Y Y Y Y Y r   ",
"  $ I Y T Y I Y I Y I I T ] l.T.l.T.`.KXIX#Xl.l.z.T.z.T.z.T.z.T.l.l.T.z.tXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXGXz.x.T.T.T.;.T.T.T.;.T.T.T.T.l.l.T.l.x.x.z.x.z.T.l.T.T.z.T.z.T.z.z.x.x.x.z.z.T.T.T.l.T.l.T.l.l.T.z.T.l.T.l.T.T.' T I Y T Y T I Y r   ",
"  $ I I I I I I I I I I I %.T.,.T.z.GXIXIXHXT.T.z.z.z.z.z.T.z.z.z.z.z.x.JXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXm.z.;.T.T.;.;.T.T.T.T.l.l.T.T.T.l.T.z.z.z.z.z.z.z.z.l.z.z.T.z.z.z.z.z.z.z.z.l.z.T.z.T.l.T.T.T.z.T.z.T.T.l.T.T.-.I I I I I I I I r   ",
"  $ P I I P P I P I P I I >.z.z.l.7XIXIXIXIX_.z.z.z.z.z.z.z.z.z.z.z.z.#XIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIX|.z.T.;.;.T.T.T.;.T.;.T.l.T.l.l.l.l.z.z.z.z.z.z.z.z.l.z.z.l.z.z.z.z.z.z.z.z.l.z.z.l.l.T.l.l.:.z.:.z.:.l.T.:.z.z.%.P I P P I I P w   ",
"  $ H P P P P P P P P P P :.z.l.z.ZXIXIXIXIXyXz.:.z.z.z.:.z.:.z.l.z.l.nXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXwXl.;.T.T.;.T.;.T.;.T.$.T.$.l.T.l.T.z.l.z.z.z.l.z.l.z.z.l.l.z.z.l.z.l.z.z.z.l.z.l.z.l.l.l.T.z.:.l.z.z.z.:.:.T.:.l.' P P P P P V ,   ",
"  $ H F F P F F P F P F P l.:.z.m.IXIXIXIXIXVXl.z.:.:.:.:.z.:.z.l.l.z.PXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXJXmXBXPXIXIXIXIXIXIXIXlXl.T.:.;.T.$.T.$.T.;.T.l.l.l.$.T.$.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.,.z.l.:.:.z.l.:.z.:.>.P F V s 7 5 =   ",
"  + u g V V V V F F F F R :.z.:..XIXIXIXIXIXIXz.l.l.l.l.l.l.l.l.:.l. XIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXBXx.:.l.R.mXIXIXIXIXIXIXVXl.;.T.;.;.;.T.;.T.;.;.T.$.;.T.$.;.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.:.:.$.D 7 5 5 5 5 3   ",
"  + 5 5 6 7 s n V F V V ' :.:.:.tXIXIXIXIXIXIX`.l.l.;.l.l.l.;.l.:.l.gXIXIXIXIXIXIXIXIXIXIXIXIXIXIXLXx.:.:.:.:.:.BXIXIXIXIXIXZX:.;.:.T.:.;.T.;.:.T.:.$.T.T.$.$.T.:.:.:.:.:.:.:.:.:.:.l.:.:.:.:.:.l.:.:.l.:.:.:.:.:.l.:.:.:.:.:.:.:.:.;.;.@.O.| | { 5 5 5 5 5 =   ",
"  O 5 5 5 5 5 5 5 u s j L ;.:.;.gXIXIXIXIXIXIXyX;.l.;.l.;.;.;.l.:.:.AXIXIXIXIXIXIXIXIXIXIXIXIXIXIXvX:.:.:.:.:.:.m.IXIXIXIXIXJX:.$.T.$.;.:.:.:.:.$.;.T.;.$.T.;.T.:.:.;.l.:.:.:.:.:.:.;.:.:.:.:.:.;.l.:.l.:.:.:.;.:.:.:.:.;.:.:.;.#.O.| | | | | | | c 5 5 5 5 =   ",
"  O 5 5 5 5 5 5 5 4 4 5 c ..+.#.gXIXIXIXIXIXIXAX;.$.l.;.;.l.l.;.;.v.IXIXIXIXIXIXIXIXIXIXIXIXIXIXIXwX;.:.;.:.;.;.;.vXIXIXIXIXIX-.;.;.;.;.:.;.;.;.;.;.$.;.$.;.$.$.:.;.:.;.;.;.:.;.;.;.:.;.:.;.;.:.;.;.;.;.;.:.;.:.;.;.;.$.@.O.| | | | | | | | | | | ) 5 5 4 5 %   ",
"  O 4 4 3 5 3 5 4 5 3 5 c | | | yXIXIXIXIXIXIXIXm.;.;.;.;.;.;.;.;.(.IXIXIXIXIXIXIXIXIXIXIXIXIXIXIXOX;.;.;.;.;.;.;. XIXIXIXIXIX-.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.$.@.O...| | | | | | | | | | | | | | | | a 3 5 3 %   ",
"  O 4 4 5 5 5 3 4 3 3 4 z | | | uXIXIXIXIXIXIXIX%X@.#.$.;.;.;.=.;.8XIXIXIXIXIXIXIXIXIXIXIXIXIXIXIX X;.=.$.;.;.;.;.-.PXIXIXIXIX-.;.;.;.;.$.;.$.;.;.$.;.;.$.;.;.;.$.;.;.;.;.;.;.$.;.;.;.;.;.;.$.;.$.@.+.O.| | | | | | | | | | | | | | | | | | | | | | A 5 4 4 @   ",
"  O 4 3 3 3 5 3 5 3 5 3 a | | | 8XIXIXIXIXIXIXIXSX| | | | ..X.@.@.gXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIX#X;.=.$.;.$.;.$.=.CXIXIXIXIX,.$.$.$.;.$.;.$.;.$.;.$.;.;.$.$.$.$.;.$.;.$.$.$.;.$.$.@.+.O.O.| | | | | | | | | | | | | | | | | { { / ~ ^ M M c c c m c 3 4 4 @   ",
"  O 5 3 5 3 3 3 3 5 3 3 y | | | .XIXIXIXIXIXIXIXIX!.| | | | | | | NXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXwX$.$.$.$.$.$.$.$.gXIXIXIXIX-.$.$.$.$.$.$.$.$.$.$.$.$.$.$.@.$.@.@.+.O.O.O...| | | | | | | | | | | | | | | | | | { { ! m z 5 3 5 3 3 3 3 3 5 3 3 5 3 4 3 4 @   ",
"  O 3 3 3 3 3 3 3 3 3 3 4 | | | M.IXIXIXIXIXIXIXhXo.| | | | | | | HXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIX8X..O.O.O.O.O.X.+.7XIXIXIXIXo.O.@.O.O.O.O.O.O.....O.| | | | | | | | | | | | | | | | | | | | | | | | | | | { ~ c 7 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 @   ",
"  o 3 3 3 : 3 3 3 3 3 3 3 _ | | l.IXIXIXIXIXIXmX| | | | | | | | } IXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXgX| | | | | | | | M.IXIXIXIX} | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | { c 7 3 3 3 3 3 3 3 3 3 3 3 3 3 : 3 3 3 3 3 3 3 3 3 @   ",
"  o 3 3 3 3 3 : 3 : : 3 : ! | |  .IXIXIXIXIXIXQ.| | | | | | | | *.IXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXBX| | | | | | | | c.IXIXIXJX| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | M 3 3 : 3 3 3 3 3 3 : : 3 3 : 3 : 3 3 3 3 3 3 3 : 3 : @   ",
"  o : 3 : 3 : 3 3 : 3 3 : m | | } GXIXIXIXIXIXo.| | | | | | | | m.IXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXHX} | | | | | | | #.IXIXIXVX| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ^ 5 5 3 : 3 3 : : 3 : 3 : 3 3 : 3 3 : 3 : : 3 : 3 : 3 3 3 +   ",
"  o : : : 3 : 3 : : : 3 : y | | | mXIXIXIXIXIX} | | | | |  .| #.nXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXo.| | | | | | |  .IXIXIXvX| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | { a 3 3 : 3 : : : 3 : : : : 3 : : 3 : 3 : : : : 3 : : : : : : @   ",
"  O : : : : : : : : : : : 3 } | | 8XIXIXIXIXIX .| | | | | _.LXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXQ.| | | | | | | } IXIXIX8X| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ~ 5 : 3 : : : : : : : : : : : : : : : : : : : : : : : : : : : : +   ",
"  X : : : : : : : : : : : : ! | | M.IXIXIXIXIX*.| | | | | | FXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXyX| | | | | | | } IXIXIXB.| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ~ 5 3 3 : : : : : : : : : : : : : : : : : : : : : : : : : : : @   ",
"  O : = : : : : : : : : : : i | | ..PXIXIXIXIXB.| | | | | | 8XIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXJX..| | | | | | X.IXIXIX#.| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ) c 3 : : : : : : : : : : : : : : : : : : : : : : : : : : +   ",
"  X : : : = : : : = : = : : : { | | lXIXIXIXIX7X} | | | | | m.IXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIX_.| | | | | | x.IXIXAX| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | } A 4 : : : : : : : : : : : : : : : = : : = : = : : : +   ",
"  X : : : : : = = : : : = : : c | | m.IXIXIXIXmX| | | | | |  .IXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXHXo.| | | | | 3XIXIXOX| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | } m : = : = = = : = = : = : = : : = : = : : : = : +   ",
"  X = : = = = : = = : = : % = 3 } | } ZXIXIXIXPXX.| | | | | | LXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXjX..| | | *.JXIXLXo.| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | { i = = : = = = : = = = = = = = : = = = = = : +   ",
"  X : % : = = = : = = = % : % : A | | ~.IXIXIXIX`.| | | | | | DXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXGX8X XwXJXIXIX3X| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ^ : = = : = : = : = = : = = = = : : = = = +   ",
"  X : = = = = = = = = = : : % : > { | | DXIXIXIXZX} | | | | | JXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXZX .| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ( 4 : = = = = : : % : % = = % : : % = = +   ",
"  X % % : % = = = = = = % % = % = x | | !.IXIXIXIX!.| | | |  .IXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXLX-.| | | | | | | | | | | | | | | | | | | | | ..| | | | | | | | | | | | | | | | | | | | | | | | | { 8 = = % = % % % = % = = % = @ : = = O   ",
"  X = : % = % = = = % = % = % = = = / | | ZXIXLXIXJX+.| | | m.IXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXLXc.| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | { 4 @ : = = = : = = = = : @ : @ = = +   ",
"  X @ % % % % = @ = = = % = % % % % x | | #.| | X.M.M.| | | fXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXHXv.| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ) : % @ % % % % % % = % % % % @ = O   ",
"  X % % % % % % = @ = @ = = = : m } | | | | | | | | | | | | -.*.v.m..XhXFXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXIXgX@.| | | | | | | | | | | | | | | | | | | | | ..| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ! % @ = % % % % % % % % % % % @ +   ",
"  X = % % % % @ @ = @ = @ @ y { | | | | | | | | | | | | | | | | | | | | | -..XnXPXIXIXIXIXIXIXIXIXIXIXIXPXhXv.| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | i @ = % % % % % % % % % % = = O   ",
"  X @ @ @ = @ @ @ @ @ % % 4 } | | | | | | | | | | | | | | | | | | | | | | | | | ..M.7XjXVXFXJXFXZXnXwXM. .| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | { = @ % @ @ % @ @ @ % @ % @ @ O   ",
"  X @ @ @ @ @ @ @ @ @ @ % x | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ..| | | | | | | | | | | | | | | | | | | c @ @ @ @ @ @ @ @ @ @ @ @ @ O   ",
"  X @ @ @ @ @ @ @ @ @ @ # 8 | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ..| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | } : @ @ @ @ @ @ @ @ @ @ @ @ O   ",
"  . + @ + @ @ @ @ @ + @ + % f } | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ..| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | m % + @ @ + @ + @ @ @ @ @ O   ",
"  X @ @ @ @ + @ + @ @ @ + @ @ > A } | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | } % # @ + @ @ @ + @ + @ @ O   ",
"  X + + + + @ @ + + + + @ @ + + + % 0 b S ! / / _ | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | x + @ + + + + @ @ + + + X   ",
"  . + + @ + + @ + + @ + + @ + + + @ + + + + + + % ~ | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ( + + + @ + + @ + + + @ O   ",
"  . + + + + + + + + + + + + + + + + + + + + + + + % ! | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | > + + + + + + + + + + X   ",
"  . + + + + + + + + + + + + + + + + + + + + + + + + + S | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | v + + + + + + + + + + O   ",
"  . + + + + + + + O + + + + + + + + + + + + + + O + + + v | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | } { } _ { _ } | | | | | | | | | | | | | | | | | | | | | ( + O + + + + + + + + X   ",
"  . O + O + O + + O + + O + + O + + + O + O O + + + + + + i } | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ) S m f 0 > > % # O + O + + O O + @ > i b A ( } | | | | | | | | | | | | | | | + + + + + O + + O + X   ",
"  . + + + O + O O + O + + + O + O O + O O + + O O O O O O O > ) | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | / b 8 + + O O O + # O + O O + + O O + + O O + O O O + + > i Z ( | | | | | | | | | | | 8 O O + O + O O + O X   ",
"    O O O + O + + O + O O O + O + + O + O O + + O + O + O + O + Z | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ! f % O O O + O + O O O O O O + O + O + O + O + O O O + + O + O + O + # 0 Z _ | | | | | | | f O O O + O O + O O X   ",
"  . + O O O O O O O O O + O O O O O O O + O O O O O O + O O O O O - / | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | ! i # O O O O + O O O O O + + O O O + O O O O O O O + O O O O O O O O O + O O O O O - x ( | | | | Z O O + O O O + O O X   ",
"  . + O O O O O O o O O O O O O O O O O O O O O O O O O O O O O O O O 9 ( | | | | | | | | | | | | | | | | | | | | | | | | | | | ~ f # O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O > Z } | A O O O O O O O O O X   ",
"    O o O o O O O O O O O O o O O O O O O O O O O O O O O O O O O O O O O 8 S | | | | | | | | | | | | | | ..| | | | | | } S i # o o O O O O O O O O O O O O o O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O o o # f Z O O o O O o O O O .   ",
"  . O o O O O o O O o O O O O O o o o O o O O o O O o o O O O o O o O o o o O # 0 Z ( | | | | | | | | | ....| { / Z i - O o o o o O o o o O O o O o o O o O O O O O o o O O o O O o O O o O O O O o O O O o O O o O X O o O o O O o O o O o O O O O O O o O X   ",
"  . o o o O X O o o o o o O X o o O O o o o o o O o o O o o o o o o o o o O o o o o O O % 8 0 f f f i i > - # o o o o o o o o o o o o O o o O o o O o o o o o o o o o O o o o o o o o o X O X O X O O X o o o o o O X O O o o O o o o O o o o o O o o o o O .   ",
"    O X O o o o X o o o o o O o o O o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o O o o o o o o o o o O o o o o o o o o o o o o o o O o o o O X   ",
"    X O o X O X o o o o X o X o X X X X o o o o X o o o X o o X o X X o X o o o o X o o o o X o o o o o o o o o o o o o o o o o o o X o o o X o o o o X o o o o X o o o o X o X o o o X X O X X X X X o O X o o o X X o X X X o o o o o o o X o X X o o X X .   ",
"  . X X X X o X X X X X X o X o X o X O X X o X X o o X X o X X X o o X X o X X X o X X X X X o o o X X X X o X o o X X X X o X X X X X X X X o o X X o X X X X X o o X X o X o o X X o X X X o X X o o X o X X X o X X X o X X o X X X X o X o X X X X o X .   ",
"    X X X X X o X X X o X X X X X X X X X X X X X X X X X X X o X o X X X X o X X X X X o X X X X X X X X X X X X X X X X X X X o X o X o X X X X X X X X X X X X X X X X X X X X X X X X o o X o X X X X X X X X X X o o X X o X X X X X X X X X o o X X o     ",
"    X X . X X X X X X X X X X X X X . X X X X X X . X X X X X . X X X X X X X X X X X X X X X X X X X X X X X X X X . X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X . X X X X X X X X X X X . X X X X X . X .   ",
"    . X X X X X X X . X X . X X X X X X . X X X X X . X X X X X X X X . X X X X X . X X X . X . X X . X X . X X . X X X X X . X X X X . X X X . X X X X X . X X X X X . X X X X X . X X X . X . X X . X X . X X . X X X X X . X X X . X X X X X X . X X X X     ",
"    X X X . X . . X X X . X . X . X . X X X . X . X . X . X . X X . X . . X . . . X . X X X . X . X X X . X . X X X X X . X . X X X X . X . . X . . X . . X . . X . X . . X . . . X . X X X . X . X X X . X . X X X X X . X . X . X . X X X X X X X X X . X     ",
"UX  . . X . X . . . . . X . X . . X . . . X . X . X . X . X . . . X . X . X . X . X . . . X . X . . . . X . X . . . . X . . X . . . X . . X . X . X . X X . . X . X . X . X . X . X . . . X . X . . . . X . X . . . . X . . X . . . X . . . . . . . . . X .     ",
"UX    . . . X . . X . . . . X . . X X . . . . . X . . X X . . . . . . . X . . . . X . X . . . . . X . . . . . X . X . . . . . . . . . . . . . . . X . . . X . . . . . . X . . . . X . X . . . . . X . . . . . X . X . . . . . . X . . . . . . . . . . X . .   UX",
"UX    . . . . . . . . . . . . . . . . . . . . X . . . . . . . . . . . . . . . . . . . . . . . X . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . X . . . . . . . . . . . . . . . . . . . . . . . . . . . . .     UX",
"UXUX    . . . . . . . . . . . . . . . . . . . .   X . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .       UX",
"UXUX    . .   . . . . .   . .   . .   . . .   . .   . .   . . . .   . . . .   . . .   . . . .     . . . . .   . . . . . . .   . . . . . . . . . . .   . . . . . .   . . . .   . . .   . . . .     . . . . .   . . . . . . .   . . . . . . . . . . . . .     UXUX",
"UXUXUX    .   . . .     . . . . . . .     . . . .   . .     . . . . . .   . . . . . .     . . . . . . .     . . . . . .   . . . . . .     . . . . . . .   . .   . . . .   . . . . . .     . . . . . . .     . . . . . .   . . .   . . .   . . .   .   .     UXUX",
"UXUXUX        .   . . . .     .     . . . .   .   .   . . . .     .   .   .   .     . . . .   . .     . . .       .   .   .   .     . . . .   .       . .     .   .   .   .   .     . . . .   . .     . . .       .   .   .   . . .   . . .   . .         UXUXUX",
"UXUXUXUX      .   .         . .   .   .   .         . .       .   .         .     .   .   .         . . .   .     .         .     .   .   .     . .           .   .         .     .   .   .         . . .   .     .         .                     .     UXUXUXUX",
"UXUXUXUXUX        .     .             .         .       . .       .     .     .       .           .         .     .     .     .       .               . . .       .     .     .       .           .         .     .     .     .   . .     .             UXUXUXUX",
"UXUXUXUXUXUX                          .                                               .                       .                       .                                               .                       .                                       UXUXUXUXUX",
"UXUXUXUXUXUXUX                                                                                                                                                                                                                                    UXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUX                                                                                                                                                                                                                              UXUXUXUXUXUXUXUX",
"UXUXUXUXUXUXUXUXUXUXUX                                                                                                                                                                                                                    UXUXUXUXUXUXUXUXUXUXUX"
};
#if defined ALLEGRO_WITH_XWINDOWS && defined ALLEGRO_USE_CONSTRUCTOR
extern void *allegro_icon;
CONSTRUCTOR_FUNCTION(static void _set_allegro_icon(void));
static void _set_allegro_icon(void)
{
    allegro_icon = allegico_xpm;
}
#endif
